name: Build & Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on version-style tags (e.g., v1.0.0)

permissions:
  contents: write  # Required for creating a release and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            gcc \
            g++ \
            mingw-w64

      - name: Build both Linux and Windows binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Package binaries
        run: |
          mkdir -p dist
          tar -C build -czf dist/cCalcApp-${{ github.ref_name }}-linux-amd64.tar.gz linux/main
          tar -C build -czf dist/cCalcApp-${{ github.ref_name }}-windows-x86_64.tar.gz windows/main.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          files: |
            dist/cCalcApp-${{ github.ref_name }}-linux-amd64.tar.gz
            dist/cCalcApp-${{ github.ref_name }}-windows-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
